try to fix publish issue

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,6 +19,13 @@ jobs:
           chmod +x setup.sh
           ./setup.sh
 
+      - name: Verify Directory
+        run: |
+          if [ ! -d "ForceAudio" ]; then
+            echo "Error: ForceAudio directory not found!"
+            exit 1
+          fi
+
       - name: Build
         run: |
           cd ForceAudio
